// Generated by scripts/parse-cv.ts. Do not edit by hand.
// Run ./update-cv.sh to regenerate.

import type { Fellowship } from "./types";

export const fellowships: Fellowship[] = [
  {
    "name": "AERA Early Career Fellowship",
    "awarder": "American Educational Research Association",
    "year": 2024
  },
  {
    "name": "Spencer Foundation Dissertation Fellowship",
    "awarder": "Spencer Foundation",
    "year": 2021
  }
];
