// Generated by scripts/parse-cv.ts. Do not edit by hand.
// Run ./update-cv.sh to regenerate.

import type { Project } from "./types";

export const projects: Project[] = [
  {
    "title": "Inclusive Classroom Analytics",
    "startYear": 2024,
    "endYear": 2026,
    "role": "Principal Investigator",
    "funder": "National Science Foundation",
    "summary": "An IRB-approved study examining multimodal engagement in K-12 classrooms."
  },
  {
    "title": "Peer Collaboration Platform",
    "startYear": 2023,
    "endYear": 2024,
    "role": "Co-Investigator",
    "funder": "Institute Internal Grant",
    "summary": "A browser-based platform for supporting peer review in undergraduate writing courses."
  }
];
