// Generated by scripts/parse-cv.ts. Do not edit by hand.
// Run ./update-cv.sh to regenerate.

import type { Publication } from "./types";

export const publications: Publication[] = [
  {
    "authors": [
      "Doe, J.",
      "Smith, A. B."
    ],
    "year": 2025,
    "title": "Evidence for cross-modal learning gains in classroom settings",
    "venue": "Journal of Learning Sciences",
    "volume": "34",
    "issue": "2",
    "pages": "145-172",
    "doi": "https://doi.org/10.1000/jls.2025.0001"
  },
  {
    "authors": [
      "Doe, J.",
      "Lee, H.",
      "Chen, W."
    ],
    "year": 2024,
    "title": "Multimodal participation analytics in small-group discussions",
    "venue": "Computers & Education",
    "volume": "210",
    "pages": "104-121",
    "doi": "https://doi.org/10.1000/ce.2024.0042"
  },
  {
    "authors": [
      "Smith, A. B.",
      "Doe, J."
    ],
    "year": 2023,
    "title": "A framework for interpreting nonverbal contributions in learning",
    "venue": "Educational Researcher",
    "volume": "52",
    "issue": "7",
    "pages": "400-415"
  }
];
