// Generated by scripts/parse-cv.ts. Do not edit by hand.
// Run ./update-cv.sh to regenerate.

import type { Talk } from "./types";

export const talks: Talk[] = [
  {
    "title": "Rethinking participation in learning analytics",
    "venue": "Learning Analytics and Knowledge Conference",
    "location": "Vancouver",
    "month": "March",
    "year": 2025
  },
  {
    "title": "Cross-modal signals in group discussion",
    "venue": "AERA Annual Meeting",
    "location": "Chicago",
    "month": "April",
    "year": 2024
  },
  {
    "title": "Designing classroom tools that see students",
    "venue": "Invited Lecture",
    "location": "Stanford GSE",
    "month": "October",
    "year": 2023
  }
];
