// Generated by scripts/parse-cv.ts. Do not edit by hand.
// Run ./update-cv.sh to regenerate.

import type { TeachingItem } from "./types";

export const teaching: TeachingItem[] = [
  {
    "title": "Learning Analytics",
    "code": "EDLF 5521",
    "level": "Graduate",
    "terms": [
      "Fall 2024",
      "Spring 2025"
    ]
  },
  {
    "title": "Research Methods in Education",
    "code": "EDLF 7230",
    "level": "Doctoral",
    "terms": [
      "Fall 2023",
      "Fall 2024"
    ]
  },
  {
    "title": "Introduction to Educational Research",
    "code": "EDLF 3010",
    "level": "Undergraduate",
    "terms": [
      "Spring 2024"
    ]
  }
];
