const HEADER =
  "// Generated by scripts/parse-cv.ts. Do not edit by hand.\n" +
  "// Run ./update-cv.sh to regenerate.\n\n";

export function toTypeScript<T>(options: {
  exportName: string;
  typeName: string;
  items: T[];
}): string {
  const { exportName, typeName, items } = options;
  const body = JSON.stringify(items, null, 2);
  return (
    HEADER +
    `import type { ${typeName} } from "./types";\n\n` +
    `export const ${exportName}: ${typeName}[] = ${body};\n`
  );
}
